#!/usr/bin/env python3
"""Create a uniformly spaced subset from BEHAVIOR raw episode paths."""

import argparse
import math
import re
from collections import defaultdict
from pathlib import Path
from typing import Dict, Iterable, List, Sequence


TASK_RE = re.compile(r"/(task-\d+)/episode_\d+\.hdf5$")


def _read_episode_paths(path: Path) -> List[str]:
    episodes: List[str] = []
    for line_number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if TASK_RE.search(stripped) is None:
            raise ValueError(f"Invalid BEHAVIOR episode path at {path}:{line_number}: {stripped}")
        episodes.append(stripped)
    return episodes


def _group_by_task(paths: Iterable[str]) -> Dict[str, List[str]]:
    grouped: Dict[str, List[str]] = defaultdict(list)
    for episode_path in paths:
        match = TASK_RE.search(episode_path)
        if match is None:
            raise ValueError(f"Invalid BEHAVIOR episode path: {episode_path}")
        grouped[match.group(1)].append(episode_path)
    return dict(grouped)


def _uniform_indices(total: int, count: int) -> List[int]:
    if count <= 0:
        return []
    if count >= total:
        return list(range(total))
    return [min(total - 1, math.floor((idx + 0.5) * total / count)) for idx in range(count)]


def _sample_uniform(paths: Sequence[str], count: int) -> List[str]:
    return [paths[idx] for idx in _uniform_indices(len(paths), count)]


def _count_from_fraction(total: int, fraction: float) -> int:
    if fraction <= 0:
        return 0
    if fraction >= 1:
        return total
    return max(1, round(total * fraction))


def _allocate_total_count(grouped: Dict[str, List[str]], target_count: int) -> Dict[str, int]:
    total = sum(len(paths) for paths in grouped.values())
    if target_count >= total:
        return {task: len(paths) for task, paths in grouped.items()}

    raw_allocations = []
    remaining = target_count
    for task, paths in grouped.items():
        exact = target_count * len(paths) / total
        base = min(len(paths), math.floor(exact))
        raw_allocations.append((exact - base, task))
        remaining -= base

    allocation = {task: min(len(paths), math.floor(target_count * len(paths) / total)) for task, paths in grouped.items()}
    for _, task in sorted(raw_allocations, reverse=True):
        if remaining <= 0:
            break
        if allocation[task] < len(grouped[task]):
            allocation[task] += 1
            remaining -= 1
    return allocation


def build_subset(
    input_list: Path,
    *,
    fraction: float,
    target_count: int | None,
    episodes_per_task: int | None,
    mode: str,
) -> List[str]:
    paths = _read_episode_paths(input_list)
    if not paths:
        raise ValueError(f"No episode paths found in {input_list}")

    if mode == "global":
        count = target_count if target_count is not None else _count_from_fraction(len(paths), fraction)
        return _sample_uniform(paths, count)

    grouped = _group_by_task(paths)
    selected: List[str] = []
    if episodes_per_task is not None:
        allocation = {task: min(len(task_paths), episodes_per_task) for task, task_paths in grouped.items()}
    elif target_count is not None:
        allocation = _allocate_total_count(grouped, target_count)
    else:
        allocation = {task: _count_from_fraction(len(task_paths), fraction) for task, task_paths in grouped.items()}

    for task in sorted(grouped):
        selected.extend(_sample_uniform(grouped[task], allocation[task]))
    return selected


def _write_output(path: Path, selected: Sequence[str], *, input_list: Path, args: argparse.Namespace) -> None:
    lines = [
        "# One BEHAVIOR raw episode Hugging Face path per line.",
        f"# Generated by {Path(__file__).name}.",
        f"# Source: {input_list}",
        f"# Mode: {args.mode}",
        f"# Fraction: {args.fraction}",
        f"# Target count: {args.target_count}",
        f"# Episodes per task: {args.episodes_per_task}",
        f"# Selected episodes: {len(selected)}",
        "",
        *selected,
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")


def parse_args() -> argparse.Namespace:
    script_dir = Path(__file__).resolve().parent
    parser = argparse.ArgumentParser(
        description="Uniformly sample BEHAVIOR raw episode paths into a smaller input list."
    )
    parser.add_argument("--input-list", type=Path, default=script_dir / "behavior_paths.txt")
    parser.add_argument("--output-list", type=Path, default=script_dir / "behavior_uniform_subset_paths.txt")
    parser.add_argument(
        "--fraction",
        type=float,
        default=0.1,
        help="Fraction to sample when neither --target-count nor --episodes-per-task is set.",
    )
    parser.add_argument("--target-count", type=int, default=None, help="Approximate total number of episodes to keep.")
    parser.add_argument("--episodes-per-task", type=int, default=None, help="Keep up to this many episodes per task.")
    parser.add_argument(
        "--mode",
        choices=("task", "global"),
        default="task",
        help="Sample uniformly within each task or across the whole list.",
    )
    args = parser.parse_args()

    if args.fraction < 0:
        parser.error("--fraction must be non-negative")
    if args.target_count is not None and args.target_count < 0:
        parser.error("--target-count must be non-negative")
    if args.episodes_per_task is not None and args.episodes_per_task < 0:
        parser.error("--episodes-per-task must be non-negative")
    if args.target_count is not None and args.episodes_per_task is not None:
        parser.error("--target-count and --episodes-per-task are mutually exclusive")
    return args


def main() -> None:
    args = parse_args()
    selected = build_subset(
        args.input_list,
        fraction=args.fraction,
        target_count=args.target_count,
        episodes_per_task=args.episodes_per_task,
        mode=args.mode,
    )
    _write_output(args.output_list, selected, input_list=args.input_list, args=args)
    print(f"Wrote {len(selected)} episodes to {args.output_list}")


if __name__ == "__main__":
    main()
